[package]
name = "Idle_Game_Rust"
version = "0.1.0"
authors = ["Mitchell Fream <m1fream@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
